channels:
  - defaults
dependencies:
  - pip
  - python=3.8
  - autopep8
  - pylint
  - ipykernel
  - networxk=2.5
  - matplotlib=3
  - tqdm=4.59
  - pip:
      - emojis~=0.6
      - decorator>=5.0.7
